image: $SKA_K8S_TOOLS_BUILD_DEPLOY

variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - lint
  - build
  - test
  - .post
  - scan
  - publish
#  - pages # Enable when we have documentation

include:
    - project: 'ska-telescope/templates-repository'
      file: "gitlab-ci/includes/python.gitlab-ci.yml"
    - project: 'ska-telescope/templates-repository'
      file: "gitlab-ci/includes/finaliser.gitlab-ci.yml"