default:
  image: $SKA_K8S_TOOLS_BUILD_DEPLOY
  tags:
    - k8srunner

variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - lint
  - build
  - test
  - .post
  - scan
  - publish
#  - pages # Disabled because we don't have the standard SKAO-style documentation

# Modify python-test template to include oskar
python-test:
  stage: test
  script:
    - apt-get update;
      apt-get --yes install --no-install-recommends cmake wget libhdf5-dev git
    - git clone https://github.com/OxfordSKA/OSKAR.git;
      cd OSKAR;
      git checkout 2.9.4;
      mkdir build;
      cd build;
      cmake ../ ;
      make -j4;
      make install
    - pip3 install 'git+https://github.com/OxfordSKA/OSKAR.git@2.9.4#egg=oskarpy&subdirectory=python'
    - cd /builds/ska-telescope/ost/ska-ost-sim-low-station-beam
    - make python-test

include:
    - project: 'ska-telescope/templates-repository'
      file: "gitlab-ci/includes/python.gitlab-ci.yml"
    # .post step finalisers eg: badges
    - project: 'ska-telescope/templates-repository'
      file: "gitlab-ci/includes/finaliser.gitlab-ci.yml"

